import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const siteDirectory = path.join(scriptDirectory, "..", "site");
const postsDirectory = path.join(siteDirectory, "content", "posts");
const redirectsPath = path.join(siteDirectory, "public", "_redirects");

const redirects = new Map([
  ["/사이트-소개/", "/about/"],
  ["/문의하기/", "/contact/"],
  ["/개인정보처리방침/", "/privacy/"],
  ["/개인정보-처리방침/", "/privacy/"],
  ["/면책조항/", "/disclaimer/"],
  ["/건강정보-면책/", "/disclaimer/"],
  ["/편집정책/", "/editorial-policy/"],
  ["/category/fitness/", "/blog/"],
  ["/category/fitness/*", "/blog/"],
  ["/category/diet/", "/blog/"],
  ["/category/diet/*", "/blog/"],
  ["/category/lifestyle/", "/blog/"],
  ["/category/lifestyle/*", "/blog/"],
  ["/category/mental-health/", "/blog/"],
  ["/category/mental-health/*", "/blog/"],
  ["/category/health-diet/", "/blog/"],
  ["/category/health-diet/*", "/blog/"],
  ["/category/expert-column/", "/blog/"],
  ["/category/expert-column/*", "/blog/"],
]);

for (const fileName of fs.readdirSync(postsDirectory).filter((name) => name.endsWith(".md"))) {
  const slug = fileName.replace(/\.md$/, "");
  const match = slug.match(/^\d{4}-\d{2}-\d{2}-(.+)$/);
  if (!match) continue;

  const source = `/${match[1]}/`;
  const target = `/blog/${slug}/`;
  const existing = redirects.get(source);

  if (existing && existing !== target) {
    throw new Error(`Conflicting redirect for ${source}: ${existing} and ${target}`);
  }

  redirects.set(source, target);
}

const lines = [
  "# Generated by scripts/generate_legacy_redirects.mjs",
  "# Keep old WordPress URLs usable while search engines adopt the current structure.",
  ...[...redirects.entries()].map(([source, target]) => `${source} ${target} 301`),
  "",
];

fs.writeFileSync(redirectsPath, lines.join("\n"), "utf8");
console.log(`Generated ${redirects.size} redirects in ${redirectsPath}`);
